classDiagram
class Vehiculo{
    -patente : string
    -marca : string
    -modelo : string
    -velocidad : double

    +Vehiculo(patente : string, marca : string, modelo : string) : void
    +Acelerar(cantidad : double) : void
    +Frenar(cantidad : double) : void
    +MostrarInfo() : void
}