classDiagram
class Libro{
    -titulo : string
    -autor : string
    -cantidaddisponible : int
    +Titulo : string
    +Autor : string
    +CantidadDisponible : int 

    +Libro(titulo : string, autor : string, cantidaddisponible : int) : void
    +PrestarLibro() : void
    +DevolverLibro() : void
    +MostrarInformacion() : void
}