classDiagram
class Producto{
    -nombre : string
    -precio : double
    -stock : int 
    +Nombre : string
    +Precio : double
    +Stock : int 

    +Producto() : void
    +MostrarInformacion() : void
}